export const OrdersHistory = [
  {
    id: 1,
    name: "Logo Design",
    image: "/team1.svg",
    tags: "Branding",
    status: "Current",
    href: "/order1",
    city: "Tbilisi",
    startDate: "2025-01-01",
    endDate: null,
  },
  {
    id: 2,
    name: "Website Redesign",
    image: "/team2.svg",
    tags: "Web Design",
    status: "Finished",
    href: "/order2",
    city: "Batumi",
    startDate: "2024-12-10",
    endDate: "2025-01-05",
  },
  {
    id: 3,
    name: "3D Model Proposal",
    image: "/team3.svg",
    tags: "3D Art",
    status: "Proposed",
    href: "/order3",
    city: "Kutaisi",
    startDate: "2025-01-05",
    endDate: null,
  },
  {
    id: 4,
    name: "Team Graphics",
    image: "/team1.svg",
    tags: "Graphics",
    status: "Current",
    href: "/order4",
    city: "Rustavi",
    startDate: "2025-01-08",
    endDate: null,
  },
  {
    id: 5,
    name: "Marketing Campaign",
    image: "/team2.svg",
    tags: "Marketing",
    status: "Finished",
    href: "/order5",
    city: "Zugdidi",
    startDate: "2024-11-20",
    endDate: "2024-12-30",
  },
  {
    id: 6,
    name: "Graffiti Design",
    image: "/team3.svg",
    tags: "Graffiti",
    status: "Proposed",
    href: "/order6",
    city: "Poti",
    startDate: "2025-01-10",
    endDate: null,
  },
  {
    id: 7,
    name: "Social Media Assets",
    image: "/team1.svg",
    tags: "Branding",
    status: "Current",
    href: "/order7",
    city: "Gori",
    startDate: "2025-01-12",
    endDate: null,
  },
  {
    id: 8,
    name: "Mobile App UI",
    image: "/team2.svg",
    tags: "UI/UX",
    status: "Finished",
    href: "/order8",
    city: "Telavi",
    startDate: "2024-12-01",
    endDate: "2024-12-20",
  },
  {
    id: 9,
    name: "Urban Art Proposal",
    image: "/team3.svg",
    tags: "Graffiti",
    status: "Proposed",
    href: "/order9",
    city: "Sighnaghi",
    startDate: "2025-01-15",
    endDate: null,
  },
];
