name: Deploy to Vercel

on:
  push:
    branches:
      - main  # the branch you want to deploy from
      - pre_deploy  # the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
